### ISSUE TITLE
Linting errors

### ISSUE THREAD

**Issue by jorge-gasca** [jorge-gasca/website#6]
There are currently some linting errors that need to be fixed. To reproduce the issue, [download golang-ci lint](https://github.com/golangci/golangci-lint#install) and run it at the root of the repo. 
```bash
golangci-lint run       
handlers/handlers.go:35:11: Error return value of `t.Execute` is not checked (errcheck)
        t.Execute(w, homePageData{Title: "Test", Background: backgroundImagePath})
                 ^
main.go:33:24: Error return value of `http.ListenAndServe` is not checked (errcheck)
        go http.ListenAndServe(":http", certManager.HTTPHandler(nil))
```

**Comment by jorge-gasca** [comment]
@EduardoGascaCervantes You should set up your Go environment using this guide https://golang.org/doc/install#install

**Comment by EduardoGascaCervantes** [comment]
@jorge-gasca I've made some progress on the error checking in handlers.go, but I am having an issue with the "go" statement in main.go. According to https://golang.org/ref/spec , the function is run simultaneously in a different goroutine and the return values (like the error) are discarded after the function completes. I'm not sure how to implement an error check in this situation, any advice would be appreciated. 
![image](https://user-images.githubusercontent.com/40374488/69380755-2805ba80-0c81-11ea-8cef-d7031c21c8a7.png)

**Comment by EduardoGascaCervantes** [comment]
Ok, it looks like I can return save the returned error of the function through a channel. I will keep investigating.
